[build]
  publish = ".next"
  command = "npm ci && npx prisma generate && npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  PRISMA_CLI_BINARY_TARGETS = "native,rhel-openssl-1.0.x"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@prisma/client", "prisma"]

# API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/*"
  status = 200

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["file"]}
  force = false
