[build]
  command = "npm ci && npx prisma generate && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  SKIP_ENV_VALIDATION = "true"
  PRISMA_CLI_BINARY_TARGETS = "rhel-openssl-1.0.x,linux-musl,debian-openssl-1.1.x"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@prisma/client", "prisma"]
